# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "gomod"
    directory: "/autodeploy"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "gomod"
    directory: "/autodeploy/examples/helloworld"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "gomod"
    directory: "/in-cluster-image-registry"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "gomod"
    directory: "/ktesting"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/ap/images/ap-golang"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/autodeploy/images/autodeploy-controller"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/autodeploy/examples/helloworld/images/examples-helloworld"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/in-cluster-image-registry/images/in-cluster-image-registry-node-agent"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
